### PR TITLE
driver: fix image_pull_timeout

### LINKED ISSUE #207: Default `image_pull_timeout` exceeds `client_http_timeout`
The default `image_pull_timeout` of 5 minutes exceeds the default `client_http_timeout` of 60 seconds. The **actual** image pull timeout is effectively 60s by default.

I found it a bit confusing that these defaults contradict the docs: _image_pull_timeout ... cannot be longer than the client_http_timeout_. While debugging an issue where my image pulls were timing out on my slow Internet connection, I realized the client timeout needed to be bumped to match the pull timeout.

I'm trying to understand the reasoning for these defaults? Is it to establish a reasonable image timeout in the event someone raises the client timeout? I would propose that the client timeout is raised to match the image timeout. I'm happy to open a PR if this is makes sense? Thank you!

### PR DESCRIPTION
**Pull request by lgfa29**
Previously the value for `image_pull_timeout` was being capped by `client_http_timeout` because the image pull request used the same HTTP client as other requests.

Increasing `client_http_timeout` in order to be able to set a higher `image_pull_timeout` is not a good option since it requires updating all client's configuration. It also affects all other HTTP requests, which may not be desirable.

The change creates a separate client for slow operations that don't have a timeout configured. Operation timeout is controlled using a ContextWithTimeout().

Closes #207

### CODE REVIEW

File: driver_test.go [hunk 1]
```diff
@@ -1914,6 +1928,91 @@ func startDestroyInspectImage(t *testing.T, image string, taskName string) {
...
+// driver's client_http_timeout.
+//
+// This test starts a proxy on port 5000 and requires the machine running the
+// test to allow an insecure registry at localhost:5000. To run this test add
+// the following to /etc/containers/registries.conf:
+//
+// [[registry]]
+// location = "localhost:5000"
+// insecure = true
+func TestPodmanDriver_Pull_Timeout(t *testing.T) {
```
Comment (lgfa29) [inline driver_test.go:1942]: I have no idea how to test this reliably 🤷 

I couldn't find any documentation on how to make a Podman API request to ignore insecure TLS so this needs to be configured in the host.

**Comment by courtland** [comment]
lgtm. Thank you.

File: driver_test.go (hunk 1 above)
Comment (jdoss) [reply driver_test.go:1942]: This is the correct way to do an insecure registry. I use `insecure = true` when firing up an ephemernal registry for local development.

**Review by jdoss — APPROVED** [review]

**Review by tgross — APPROVED** [review]
LGTM

File: driver_test.go (hunk 1 above)
Comment (lgfa29) [reply driver_test.go:1942]: Thanks! I was looking for a way to test this that wouldn't require a specific setting on the local machine, but I couldn't figure out a way, so that's the best we have for now 😅
